# Generated by Django 2.1 on 2019-08-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subs',
            new_name='Sub',
        ),
    ]
