# Generated by Django 2.1 on 2019-08-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190804_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub',
            options={'verbose_name': 'Sub', 'verbose_name_plural': 'Subs'},
        ),
    ]
