# Generated by Django 2.1 on 2019-09-08 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_in_basket'),
        ('orders', '0009_productsinfavorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinfavorites',
            name='order',
        ),
        migrations.AddField(
            model_name='productsinfavorites',
            name='image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductImg'),
        ),
    ]
