# Generated by Django 2.1 on 2019-09-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190908_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinfavorites',
            name='image',
        ),
    ]
