# Generated by Django 2.1 on 2019-11-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_productsinfavorites_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
    ]
