# Generated by Django 3.0.3 on 2020-07-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200302_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryInNavbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категория товара в Navbar',
                'verbose_name_plural': 'Категории товаров в Navbar',
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Подкатегория товара',
                'verbose_name_plural': 'Подкатегории товаров',
            },
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Основная категория товара', 'verbose_name_plural': 'Основные категории товаров'},
        ),
        migrations.AddField(
            model_name='product',
            name='categoryInNavbar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategoryInNavbar'),
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductSubCategory'),
        ),
    ]
