# Generated by Django 3.0.3 on 2020-07-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200710_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='products.ProductCategory'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='categoryInNavbar',
        ),
        migrations.AddField(
            model_name='product',
            name='categoryInNavbar',
            field=models.ManyToManyField(to='products.ProductCategoryInNavbar'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='subCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ManyToManyField(to='products.ProductSubCategory'),
        ),
    ]
