# Generated by Django 3.0.3 on 2020-07-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200710_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='products.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoryInNavbar',
            field=models.ManyToManyField(blank=True, to='products.ProductCategoryInNavbar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCategory',
            field=models.ManyToManyField(blank=True, to='products.ProductSubCategory'),
        ),
    ]
