# Generated by Django 3.0.3 on 2020-07-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200710_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='nameEnglish',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productcategoryinnavbar',
            name='nameEnglish',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='nameEnglish',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
