# Generated by Django 3.0.3 on 2020-07-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200710_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategory',
            name='name',
        ),
    ]
