# Generated by Django 3.0.3 on 2020-07-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_productsubcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
